# fly.toml app configuration file generated for fonotherapp-web on 2024-07-21T11:39:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fonotherapp-web'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/"

[[restart]]
  policy = "always"
  retries = 10
  processes = ["app"]
  
[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
